### PR TITLE
Export `ReadlineBytes` (part of an exposed signature)

### PR DESCRIPTION
**Pull request by tbu-**

### CODE REVIEW

**Comment by GBGamer** [comment]
Cool beans.

**Comment by GBGamer** [comment]
Would you like to take this over? It's not like I've ever paid much attention to this repo.

**Comment by tbu-** [comment]
I would be willing to maintain this, it's one of my dependencies.

**Comment by GBGamer** [comment]
You now have push access to readline, and I'll add readline-sys.

**Comment by GBGamer** [comment]
Are you logged into `crates.io`? I'd like to add you as a collaborator there as well.

**Comment by tbu-** [comment]
Yes, I'm logged in there. Is there anything I need to do there?

**Comment by GBGamer** [comment]
Nah, I'll add you now.

**Comment by GBGamer** [comment]
You should now be able to publish :smile:

**Pull request merged**
